### PR TITLE
headless.md and m28api.md

### PR DESCRIPTION
**Pull request by CoderSudaWuda**
Explanation of websocket connection and api.n.m28.io

### CODE REVIEW

**Comment by ABCxFF** [comment]
Nice

**Comment by CoderSudaWuda** [comment]
ez

**Comment by CoderSudaWuda** [comment]
pong isnt shuffled hwen sent from erver, but yeah ping is shuffled

**Comment by diepiodiscord** [comment]
incoming pong is shuffled too, the only ones that aren't are the 2 packets which include a version hash in them (outgoing init and incoming outdated version)

**Pull request merged**
