### PR TITLE
make the formula to convert canvas and diep units easier to read

### PR DESCRIPTION
**Pull request by Craabby**

### CODE REVIEW

**Comment by endlessXD** [comment]
oh yeah that does look better

**Comment by Craabby** [comment]
actually it doesnt work so someone who is good at math, please help lol

**Comment by endlessXD** [comment]
The second is the only wrong one if I’m right

10 * 1 canvas pixel / scalingFactor()

**Review by binary-person — CHANGES_REQUESTED** [review]
put the "10"s back in the front

**Comment by endlessXD** [comment]
@binary-person is that better

**Comment by binary-person** [comment]
no. it's fine, i can do it

**Pull request merged**
