### PR TITLE
add and publicate crypto information

### PR DESCRIPTION
**Pull request by ABCxFF**

### CODE REVIEW

**Comment by ABCxFF** [comment]
publication of further information is being held off until further notice

**Comment by ABCxFF** [comment]
What you are reading is further notice

**Comment by ABCxFF** [comment]
@endless7z can you do grammar stuff 🥺 🙏

**Comment by endless7z** [comment]
> @endless7z (and anyone else who wants) can you do grammar stuff 🥺 🙏 - then we'll merge.

ok

**Comment by endless7z** [comment]
looks good

**Comment by ABCxFF** [comment]
👍

**Pull request merged**
